# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hugsy/code/proxenet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hugsy/code/proxenet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hugsy/code/proxenet/CMakeFiles /home/hugsy/code/proxenet/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hugsy/code/proxenet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named proxenet

# Build rule for target.
proxenet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 proxenet
.PHONY : proxenet

# fast build rule for target.
proxenet/fast:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/build
.PHONY : proxenet/fast

control-server.o: control-server.c.o
.PHONY : control-server.o

# target to build an object file
control-server.c.o:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/control-server.c.o
.PHONY : control-server.c.o

control-server.i: control-server.c.i
.PHONY : control-server.i

# target to preprocess a source file
control-server.c.i:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/control-server.c.i
.PHONY : control-server.c.i

control-server.s: control-server.c.s
.PHONY : control-server.s

# target to generate assembly for a file
control-server.c.s:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/control-server.c.s
.PHONY : control-server.c.s

core.o: core.c.o
.PHONY : core.o

# target to build an object file
core.c.o:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/core.c.o
.PHONY : core.c.o

core.i: core.c.i
.PHONY : core.i

# target to preprocess a source file
core.c.i:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/core.c.i
.PHONY : core.c.i

core.s: core.c.s
.PHONY : core.s

# target to generate assembly for a file
core.c.s:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/core.c.s
.PHONY : core.c.s

http.o: http.c.o
.PHONY : http.o

# target to build an object file
http.c.o:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/http.c.o
.PHONY : http.c.o

http.i: http.c.i
.PHONY : http.i

# target to preprocess a source file
http.c.i:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/http.c.i
.PHONY : http.c.i

http.s: http.c.s
.PHONY : http.s

# target to generate assembly for a file
http.c.s:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/http.c.s
.PHONY : http.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/main.c.s
.PHONY : main.c.s

plugin-c.o: plugin-c.c.o
.PHONY : plugin-c.o

# target to build an object file
plugin-c.c.o:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/plugin-c.c.o
.PHONY : plugin-c.c.o

plugin-c.i: plugin-c.c.i
.PHONY : plugin-c.i

# target to preprocess a source file
plugin-c.c.i:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/plugin-c.c.i
.PHONY : plugin-c.c.i

plugin-c.s: plugin-c.c.s
.PHONY : plugin-c.s

# target to generate assembly for a file
plugin-c.c.s:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/plugin-c.c.s
.PHONY : plugin-c.c.s

plugin-lua.o: plugin-lua.c.o
.PHONY : plugin-lua.o

# target to build an object file
plugin-lua.c.o:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/plugin-lua.c.o
.PHONY : plugin-lua.c.o

plugin-lua.i: plugin-lua.c.i
.PHONY : plugin-lua.i

# target to preprocess a source file
plugin-lua.c.i:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/plugin-lua.c.i
.PHONY : plugin-lua.c.i

plugin-lua.s: plugin-lua.c.s
.PHONY : plugin-lua.s

# target to generate assembly for a file
plugin-lua.c.s:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/plugin-lua.c.s
.PHONY : plugin-lua.c.s

plugin-perl.o: plugin-perl.c.o
.PHONY : plugin-perl.o

# target to build an object file
plugin-perl.c.o:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/plugin-perl.c.o
.PHONY : plugin-perl.c.o

plugin-perl.i: plugin-perl.c.i
.PHONY : plugin-perl.i

# target to preprocess a source file
plugin-perl.c.i:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/plugin-perl.c.i
.PHONY : plugin-perl.c.i

plugin-perl.s: plugin-perl.c.s
.PHONY : plugin-perl.s

# target to generate assembly for a file
plugin-perl.c.s:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/plugin-perl.c.s
.PHONY : plugin-perl.c.s

plugin-python.o: plugin-python.c.o
.PHONY : plugin-python.o

# target to build an object file
plugin-python.c.o:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/plugin-python.c.o
.PHONY : plugin-python.c.o

plugin-python.i: plugin-python.c.i
.PHONY : plugin-python.i

# target to preprocess a source file
plugin-python.c.i:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/plugin-python.c.i
.PHONY : plugin-python.c.i

plugin-python.s: plugin-python.c.s
.PHONY : plugin-python.s

# target to generate assembly for a file
plugin-python.c.s:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/plugin-python.c.s
.PHONY : plugin-python.c.s

plugin-ruby.o: plugin-ruby.c.o
.PHONY : plugin-ruby.o

# target to build an object file
plugin-ruby.c.o:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/plugin-ruby.c.o
.PHONY : plugin-ruby.c.o

plugin-ruby.i: plugin-ruby.c.i
.PHONY : plugin-ruby.i

# target to preprocess a source file
plugin-ruby.c.i:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/plugin-ruby.c.i
.PHONY : plugin-ruby.c.i

plugin-ruby.s: plugin-ruby.c.s
.PHONY : plugin-ruby.s

# target to generate assembly for a file
plugin-ruby.c.s:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/plugin-ruby.c.s
.PHONY : plugin-ruby.c.s

plugin.o: plugin.c.o
.PHONY : plugin.o

# target to build an object file
plugin.c.o:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/plugin.c.o
.PHONY : plugin.c.o

plugin.i: plugin.c.i
.PHONY : plugin.i

# target to preprocess a source file
plugin.c.i:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/plugin.c.i
.PHONY : plugin.c.i

plugin.s: plugin.c.s
.PHONY : plugin.s

# target to generate assembly for a file
plugin.c.s:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/plugin.c.s
.PHONY : plugin.c.s

socket.o: socket.c.o
.PHONY : socket.o

# target to build an object file
socket.c.o:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/socket.c.o
.PHONY : socket.c.o

socket.i: socket.c.i
.PHONY : socket.i

# target to preprocess a source file
socket.c.i:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/socket.c.i
.PHONY : socket.c.i

socket.s: socket.c.s
.PHONY : socket.s

# target to generate assembly for a file
socket.c.s:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/socket.c.s
.PHONY : socket.c.s

ssl.o: ssl.c.o
.PHONY : ssl.o

# target to build an object file
ssl.c.o:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/ssl.c.o
.PHONY : ssl.c.o

ssl.i: ssl.c.i
.PHONY : ssl.i

# target to preprocess a source file
ssl.c.i:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/ssl.c.i
.PHONY : ssl.c.i

ssl.s: ssl.c.s
.PHONY : ssl.s

# target to generate assembly for a file
ssl.c.s:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/ssl.c.s
.PHONY : ssl.c.s

utils.o: utils.c.o
.PHONY : utils.o

# target to build an object file
utils.c.o:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/utils.c.o
.PHONY : utils.c.o

utils.i: utils.c.i
.PHONY : utils.i

# target to preprocess a source file
utils.c.i:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/utils.c.i
.PHONY : utils.c.i

utils.s: utils.c.s
.PHONY : utils.s

# target to generate assembly for a file
utils.c.s:
	$(MAKE) -f CMakeFiles/proxenet.dir/build.make CMakeFiles/proxenet.dir/utils.c.s
.PHONY : utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... proxenet"
	@echo "... rebuild_cache"
	@echo "... control-server.o"
	@echo "... control-server.i"
	@echo "... control-server.s"
	@echo "... core.o"
	@echo "... core.i"
	@echo "... core.s"
	@echo "... http.o"
	@echo "... http.i"
	@echo "... http.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... plugin-c.o"
	@echo "... plugin-c.i"
	@echo "... plugin-c.s"
	@echo "... plugin-lua.o"
	@echo "... plugin-lua.i"
	@echo "... plugin-lua.s"
	@echo "... plugin-perl.o"
	@echo "... plugin-perl.i"
	@echo "... plugin-perl.s"
	@echo "... plugin-python.o"
	@echo "... plugin-python.i"
	@echo "... plugin-python.s"
	@echo "... plugin-ruby.o"
	@echo "... plugin-ruby.i"
	@echo "... plugin-ruby.s"
	@echo "... plugin.o"
	@echo "... plugin.i"
	@echo "... plugin.s"
	@echo "... socket.o"
	@echo "... socket.i"
	@echo "... socket.s"
	@echo "... ssl.o"
	@echo "... ssl.i"
	@echo "... ssl.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

